
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - "ng build --prod && cp dist/index.html dist/200.html"

deploy:
  provider: script
  script: netlify deploy --site=$NETLIFY_SITEID --auth=$NETLIFY_TOKEN --dir=dist
  skip_cleanup: true
  on:
    branch: master
