
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
before_deploy: "ng build --prod && cp dist/index.html dist/200.html"
deploy:
  provider: surge
  skip_cleanup: true
  project: ./dist
  domain: piletron3000.surge.sh
  on:
    branch: master
